eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: es-server:2050  #指定服务的id
server:
  port: 2050
spring:
  application:
    name: es-server
    data:
        elasticsearch:
          cluster-name: my-ealsticsearch
          cluster-nodes: 127.0.0.1:9300 #9200是图形界面端,9300代码端