eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: course-server:2020  #指定服务的id
server:
  port: 2020
spring:
  application:
    name: course-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///hrm-course?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false