eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: page-server:2060  #指定服务的id
server:
  port: 2060
spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      listener:
        simple:
          acknowledge-mode: manual
  application:
    name: page-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///hrm-page?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
feign:
  hystrix:
    enabled: true
pagestatic:
  routingKey: hrmCourseSite