eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: redis-server:2030  #指定服务的id
server:
  port: 2030
spring:
  application:
    name: redis-server